version: '3'

services:
  hypno-ai:
    image: ghcr.io/raphaelmue/hypno-ai:latest
    ports:
      - "5000:5000"
    volumes:
      - ./app/static/voices:/app/app/static/voices
      - ./app/static/output:/app/app/static/output
    environment:
      - AUDIO_GENERATION_THREADS=4
    restart: unless-stopped
